name: derry
description: A script manager to help you define script shortcuts and use them effortlessly, and performantly.
version: 1.4.3
repository: https://github.com/frencojobs/derry

environment:
  sdk: '>=2.12.0 <4.0.0'

executables:
  derry:

dependencies:
  args: ^2.0.0
  console: ^4.0.0
  equatable: ^2.0.0
  ffi: ^2.0.0
  io: ^1.0.0
  path: ^1.0.0
  string_similarity: ^2.0.0
  yaml: ^3.0.0

dev_dependencies:
  build_runner: ^2.0.0
  build_version: ^2.0.0
  lint: ^1.0.0
  test: ^1.20.0

scripts: derry.yaml
