name: derry
description: A script manager to help you define script shortcuts and use them effortlessly, and performantly.
version: 1.4.3
repository: https://github.com/frencojobs/derry

environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  derry:

dependencies:
  args: ^2.4.1
  console: ^4.1.0
  equatable: ^2.0.5
  ffi: ^2.0.2
  io: ^1.0.4
  path: ^1.8.3
  string_similarity: ^2.0.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.4
  build_version: ^2.1.1
  lint: ^2.1.2
  test: ^1.24.3

scripts: derry.yaml
